### ISSUE TITLE
Should creating Franchises require mod/admin privileges?

### ISSUE THREAD

**Issue by connorshea** [noidedmedia/Fiction-Dock#22]
I feel like this isn't a big enough deal to require that level of authority. Thoughts?

**Comment by AnthonySuper** [comment]
I'm afraid people will start making franchises for all sorts of stupid shit.

**Comment by connorshea** [comment]
Well it isn't sustainable to do this ourselves in the long run, and giving everybody and their mother admin privileges would just cause the same problem anyway.

**Comment by connorshea** [comment]
Fixed by the Request New Franchise feature
