### ISSUE TITLE
Stories

### ISSUE THREAD

**Issue by connorshea** [noidedmedia/Fiction-Dock#3]
General:
- [x] Story Structure (#2)
- [x] Author of a story
- [x] Date published/updated
- [x] Story title
- [x] Story description (max 160 characters?)
- [x] Language
- [x] License (CC-BY-SA by default)
- [x] Belongs to a Franchise

Actions:
- [x] Favorite a story
- [x] Comment on a story
- [x] Edit/write a story (using Markdown probably)

**Comment by AnthonySuper** [comment]
Note: Story description is allowed to be very long. The story's "blurb" (which probably should be named "logline" is what's short.

**Comment by connorshea** [comment]
Done, mostly!
