### ISSUE TITLE
Move from ActiveRecord to Sequel

### ISSUE THREAD

**Issue by AnthonySuper** [noidedmedia/Fiction-Dock#38]
After reading up a bit on the [Sequel](http://sequel.jeremyevans.net/) gem, as well as [sequel-rails](https://github.com/TalentBox/sequel-rails), I've decided that using Sequel is going to be much easier to maintain. Currently, we drop into Arel for searching, which is not only [freaking disgusting](https://github.com/noidedmedia/Fiction-Dock/blob/a4488afb438b0e696e2285c03acd8a8d472c945d/lib/searcher.rb), but requires us to perform all sorts of weird hacks to ensure that stories are properly filtered. If I add more powerful searching, I suspect the feature is only going to get much, much worse.

As such, a migration is necessary. It will take some time, but I think it will be worth it in the end.

**Comment by connorshea** [comment]
[Sequel Devise](https://github.com/rosenfeld/sequel-devise)

**Comment by AnthonySuper** [comment]
This is going to take too long.
