### ISSUE TITLE
Unpublishing all chapters of a story doesn't Unpublish the story

### ISSUE THREAD

**Issue by connorshea** [noidedmedia/Fiction-Dock#56]

**Comment by AnthonySuper** [comment]
Fixed in 87c8f5382ec10e09904ebadc8d2caa6a25c47e8d

**Comment by AnthonySuper** [comment]
Note that it still does not unpublish the story, instead opting to tell the users that they must unpublish the story manually first. Should avoid "Why was my story unpublished" complaints.
